language: node_js
node_js:
  - "9"
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: pzhang87/d3bot_mk3
  bucket: d3bot-mk3-storage
  region: us-west-2
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: d3bot-mk3-storage
  key: latest.zip
  bundle_type: zip
  application: d3bot_mk3
  deployment_group: d3bot
  region: us-west-2
  on: *2
script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
