version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/d3bot_mk3
hooks:
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
    - timeout: 300
    - runas: root
  ApplicationStart:
    - location: scripts/run.sh
      timeout: 120
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ec2-user
